version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - media_data:/app/media
    ports:
      - "8001:8000" # Production port
    env_file:
      - ./backend/.env
    networks:
      - construction_network
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    volumes:
      - media_data:/usr/share/nginx/html/media
    ports:
      - "8080:80" # Production port
    depends_on:
      - backend
    networks:
      - construction_network
      - app_network

networks:
  construction_network:
    driver: bridge
  app_network:
    external: true
    name: app-network

volumes:
  media_data:
